### ISSUE TITLE
Webpack Build Android

### ISSUE THREAD

**Issue by jogboms** [sean-perkins/nativescript-task-app#1]
ERROR in Could not resolve "/+task/task.module" from "/Users/apple/Desktop/NS/nativescript-task-app/app/app.routing.ts"

https://github.com/sean-perkins/nativescript-task-app/blob/317d3b64c073b965cea250ab8c46340722f5b73a/app/app.routing.ts#L9

Needed a `.` before the path. Relative path.

**Comment by sean-perkins** [comment]
Thanks for reporting this! Updated and merged into master.
